export const mainTopics = [
   "-",
   "Arts",
   "Books",
   "Environment",
   "Feminine Sexuality",
   "Gender-based Violence",
   "Industrial Design",
   "Land Disputes",
   "Landscape Architecture",
   "Movies",
   "Music",
   "Philosophy of Science",
   "Photography",
   "Rythm",
   "Technology",
   "Transportation",
   "Videogames",
];
